# Example ESPHome configuration for QMI8658C IMU sensor
# This example is configured for an ESP32-S3 using the ESP-IDF framework

esphome:
  name: esp32s3-imu
  friendly_name: ESP32-S3 IMU Sensor

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable OTA updates
ota:
  platform: esphome

wifi:
  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "ESP32S3-IMU Fallback"

# External component reference
external_components:
  - source:
      type: local
      path: components
    components: [qmi8658]

# I2C bus configuration for ESP32-S3
# Adjust pins according to your board
i2c:
  sda: GPIO8
  scl: GPIO9
  scan: true
  id: bus_a

# QMI8658C IMU component configuration
# This creates the main component that all platforms reference
qmi8658:
  id: imu_sensor
  address: 0x6B
  update_interval: 100ms
  # Configurable ranges
  accel_range: 2G        # Options: 2G, 4G, 8G, 16G
  gyro_range: 2048DPS    # Options: 16DPS, 32DPS, 64DPS, 128DPS, 256DPS, 512DPS, 1024DPS, 2048DPS
  # ODR (Output Data Rate) controls how often the sensor samples internally.
  # Higher ODR = faster response but more power consumption. Lower ODR = smoother readings.
  accel_odr: 500HZ       # Options: 8000HZ, 4000HZ, 2000HZ, 1000HZ, 500HZ, 250HZ, 125HZ, 62.5HZ, 31.25HZ
  gyro_odr: 500HZ        # Options: 8000HZ, 4000HZ, 2000HZ, 1000HZ, 500HZ, 250HZ, 125HZ, 62.5HZ, 31.25HZ
  # Low-pass filter settings (bandwidth as % of ODR, lower = more smoothing)
  accel_lpf: 2.66%       # Options: DISABLED, 2.66%, 3.63%, 5.39%, 13.37% (default: 2.66%)
  gyro_lpf: 2.66%        # Options: DISABLED, 2.66%, 3.63%, 5.39%, 13.37% (default: 2.66%)

  # Automation triggers - fire automations without needing sensor platforms
  # on_motion: fires once when motion starts (leading edge only)
  on_motion:
    threshold: 0.5  # m/s² deviation from gravity (default: 0.5, range: 0.1-10.0)
    then:
      - logger.log: "Motion detected via on_motion trigger!"

  # on_orientation_change: fires when device orientation changes
  # The 'orientation' variable contains the new orientation string:
  # face_up, face_down, portrait, portrait_inverted, landscape_left, landscape_right, unknown
  on_orientation_change:
    then:
      - logger.log:
          format: "Orientation changed to: %s"
          args: ['orientation.c_str()']

# QMI8658C sensor platform - references the component above
# NOTE: At 100ms update_interval, raw sensor data can overwhelm Home Assistant's
# recorder. Use filters or internal: true to reduce logging overhead.
sensor:
  - platform: qmi8658
    qmi8658_id: imu_sensor

    # Approach 1: internal: true - Not exposed to Home Assistant at all.
    # Use this when you only need the values for internal ESPHome automations
    # (e.g., motion detection) but don't need them visible in HA.
    accel_x:
      id: accel_x
      internal: true
    accel_y:
      id: accel_y
      internal: true
    accel_z:
      id: accel_z
      internal: true

    # Approach 2: throttle_average - Averages readings over a period and sends
    # once. Good for gyroscope where you want smoothed values in HA.
    gyro_x:
      name: "Gyroscope X"
      id: gyro_x
      filters:
        - throttle_average: 5s
    gyro_y:
      name: "Gyroscope Y"
      id: gyro_y
      filters:
        - throttle_average: 5s
    gyro_z:
      name: "Gyroscope Z"
      id: gyro_z
      filters:
        - throttle_average: 5s

    # Approach 3: delta - Only sends when the value changes significantly.
    # Good for temperature which changes slowly.
    temperature:
      name: "IMU Temperature"
      id: imu_temp
      filters:
        - delta: 0.5  # Only send if temperature changes by 0.5°C

    # Approach 4: Combine throttle + delta for tilt angles.
    # Only sends every 5s AND only if the angle changed by more than 1 degree.
    pitch:
      name: "Pitch"
      id: pitch
      state_class: measurement  # Explicit state_class (use "" to disable statistics)
      filters:
        - delta: 1.0
        - throttle: 5s
    roll:
      name: "Roll"
      id: roll
      state_class: measurement
      filters:
        - delta: 1.0
        - throttle: 5s

# Motion detection binary sensor
binary_sensor:
  - platform: qmi8658
    qmi8658_id: imu_sensor
    motion:
      name: "Motion Detected"
      threshold: 0.5  # m/s² deviation from gravity

# Orientation detection text sensor
text_sensor:
  - platform: qmi8658
    qmi8658_id: imu_sensor
    orientation:
      name: "Device Orientation"
